document.writeln("<footer class=\'footer\'>");
document.writeln("	<div class=\'container\'>");
document.writeln("		<div class=\'copyright f-ptb24\'>");
document.writeln("			<div class=\'container\'>");
document.writeln("				<p class=\'text-center f-mb20\'>东润环能UED团队</p>");
document.writeln("				<p class=\'text-center f-mb20\'>康如涛  && 谢波 && 刘京奇 && 高爱宁 && 高月娇 && 任珊珊 && 正在期待的你</p>");
document.writeln("				<p class=\'text-center\' >Copyright  2017  版权所有 <a href=\'#\' target=\'_blank\' >北京东润环能科技股份有限公司</a> Powered by <a href=\'#\' target=\'_blank\'>WordPress</a></p>");
document.writeln("");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("");
document.writeln("</footer>");