document.writeln("<nav class=\'navbar navbar-default navbar-static-top navbar-fixed-top\'>");
document.writeln("		<div class=\'container\'>");
document.writeln("			<div class=\'navbar-header\'>");
document.writeln("				<button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#bs-example-navbar-collapse-1\' aria-expanded=\'false\'>");
document.writeln("					<span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("					<span class=\'icon-bar\'></span>");
document.writeln("					<span class=\'icon-bar\'></span>");
document.writeln("					<span class=\'icon-bar\'></span>");
document.writeln("				</button>");
document.writeln("				<a class=\'navbar-brand\' href=\'#\'><img src=\'images/logo.png\'></a>");
document.writeln("			</div>");
document.writeln("");
document.writeln("			<div class=\'collapse navbar-collapse navbar-right clearfix\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("				<ul class=\'nav navbar-nav pull-left\'>");
document.writeln("					<li class=\'active\'>");
document.writeln("						<a href=\'#\'>首页 <span class=\'sr-only\'>(current)</span><span class=\'m-line\' ></span></a>");
document.writeln("						");
document.writeln("					</li>");
document.writeln("					<li style=\'position: relative;\'>");
document.writeln("						<a href=\'#\'>文章动态<span class=\'m-line\' ></span></a>");
document.writeln("						");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'#\'>关于我们<span class=\'m-line\' ></span></a>");
document.writeln("");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("				<form class=\'navbar-form pull-right\'>");
document.writeln("					<div class=\'input-group\'>");
document.writeln("						<input type=\'text\' class=\'form-control\' placeholder=\'请输入关键词搜索…\'>");
document.writeln("						<span type=\'submit\' class=\'input-group-addon\'><a href=\'#\'><span class=\'glyphicon glyphicon-search\'></span></a></span>");
document.writeln("					</div>");
document.writeln("					");
document.writeln("				</form>");
document.writeln("				");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</nav>");